version: '3.6'
services:
  # mzproxy:
  #  build: ./haproxy
  #  image: 'docker.io/library/haproxy:latest'
  #  restart: always
  #  ports:
  #    - "8080:8080"
  #  volumes:
  #    - '/data/container_files/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg'

  gitlab:
    image: 'gitlab/gitlab-ee:14.10.5-ee.0'
    restart: always
    container_name: gitlab
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'http://176.34.48.28'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['time_zone'] = 'Asia/Tokyo'
        gitlab_rails['monitoring_whitelist'] = ['0.0.0.0/0']
        gitlab_rails['backup_upload_connection'] = {
          provider: 'AWS',
          region: 'ap-northeast-1',
          use_iam_profile: true
        }
        #gitlab_rails['backup_upload_remote_directory'] = ''
        gitlab_rails['backup_keep_time'] = 604800
        # Amazon SES
        gitlab_rails['smtp_enable'] = false
        #gitlab_rails['smtp_address'] = "email-smtp.us-west-2.amazonaws.com"
        #gitlab_rails['smtp_port'] = 587
        #gitlab_rails['smtp_user_name'] = "AKIAAAAAAAAAAAAAAAAA"
        #gitlab_rails['smtp_password'] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        #gitlab_rails['smtp_domain'] = "aws.local"
        #gitlab_rails['smtp_authentication'] = "login"
        #gitlab_rails['smtp_enable_starttls_auto'] = true
        # Add any other gitlab.rb configuration here, each on its own line
        #unicorn['worker_processes'] = 2
        puma['worker_processes'] = 2
        postgresql['shared_buffers'] = "512MB"
        prometheus_monitoring['enable'] = false

        #gitlab_rails['gitlab_shell_ssh_port'] = 22232

        #Pages
        pages_external_url 'https://pages.dev.example.com'
        gitlab_pages['enable'] = true
        gitlab_pages['access_control'] = true
        pages_nginx['listen_port'] = 80
        pages_nginx['listen_https'] = false
        gitlab_pages['internal_gitlab_server'] = 'http://gitlab:80'

    #Add memory
    mem_limit: 5.5g
    ports:
      - '80:80'
      #- '443:443'
      - '22232:22'
    volumes:
      - '/docker/container_files/gitlab/config:/etc/gitlab'
      - '/docker/container_files/gitlab/logs:/var/log/gitlab'
      - '/docker/container_files/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'

  nexus:
    # build: ./nexus
    image: 'docker.io/sonatype/nexus3:latest'
    restart: always
    container_name: nexus
    hostname: 'nexus.example.com'
    #environment:
      #For small team 8GB memory.(repositories < 20 ,total blobstore size < 20GB , single repository format type.)
      #INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m"
      #For medium team 16GB memory.(repositories < 50 ,total blobstore size < 200GB , a few repository formats.)
      #exp: INSTALL4J_ADD_VM_PARAMS: "-Xms4G -Xmx4G -XX:MaxDirectMemorySize=6717m"
    ports:
      - "8081:8081"
    volumes:
      #make folder(/data/container_files/nexus/nexus-data) and Require command "chown -R 200 nexus-data"
      #adminpassword: /data/container_files/nexus/nexus-data/admin.password
      - '/docker/container_files/nexus/nexus-data:/nexus-data'
      - '/docker/container_files/nexus/etc/gitlabauth.properties:/opt/sonatype/nexus/etc/gitlabauth.properties'


