version: '3.4'

services:
   db:
     # image: 706357943586.dkr.ecr.ap-northeast-1.amazonaws.com/tada-wordpress:tag1_tada-mysql
     image: docker.io/library/mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: /run/secrets/mysql_secrets_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_PASSWORD: /run/secrets/mysql_secrets_password
       MYSQL_USER: wordpress
     secrets:
       - mysql_secrets_root_password
       - mysql_secrets_password

   wordpress:
     depends_on:
       - db
     # image: 706357943586.dkr.ecr.ap-northeast-1.amazonaws.com/tada-wordpress:tag1_tada-wordpress
     image: docker.io/library/wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: /run/secrets/mysql_secrets_password
     secrets:
       - mysql_secrets_password

volumes:
    db_data:
secrets:
  mysql_secrets_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_secrets_password:
    file: ./secrets/mysql_password.txt
